### ISSUE TITLE
Does not work on dotnet core 2.2

### ISSUE THREAD

**Issue by s-krawczyk** [greuelpirat/DeepCopy#19]
Tried to use it on dotnet core. But without success. Your tests in AppVeyor are executed by full framework not dotnet core. when you try to run this by dotnet.exe all fails. found it in my project. Spent some time to investigate and here is the result. Can you try it?

![image](https://user-images.githubusercontent.com/9395791/72903499-9ae8eb80-3d2d-11ea-844f-ce5217672754.png)

**Comment by greuelpirat** [comment]
hm. my test run had no fails:

![image](https://user-images.githubusercontent.com/16866222/72919441-c7116600-3d47-11ea-82fb-460793414283.png)

I know the build-tests are incomplete. But I was just happy to make work :-)

**Comment by s-krawczyk** [comment]
That's strange. I can reproduce this on build agents. Other people computers etc.. Any proposition how we can investigate this?

**Comment by greuelpirat** [comment]
first I will try to get the core-tests running on AppVeyor. I will have a look this weekend.

**Comment by greuelpirat** [comment]
I have updated the build and the tests run now for core as well. and are successful.

**Comment by greuelpirat** [comment]
I close this
