### ISSUE TITLE
Is it possible to use DeepCopy 1.0.12 with Fody 4.2.1?

### ISSUE THREAD

**Issue by ekalchev** [greuelpirat/DeepCopy#20]
I am using visual studio 2017 and I would like to use your weaver but the dependency to Fody 6 prevent me from using it with VS2017. I can downgrade Fody to 4.2.1 that is compatible with VS2017 but I am not sure if this might cause some issues.

**Comment by greuelpirat** [comment]
DeepCopy `1.0.7` was latest version that was built with Fody `4.2.1`. So that should work out fine. But it was quiet buggy, so I would not recommend it. I see if I can downgrade the setup.

**Comment by greuelpirat** [comment]
I pushed a branch configured with Fody 4.2.1. All tests passed. 

You can download the package here: 
https://ci.appveyor.com/project/greuelpirat/deepcopy/builds/31050729/artifacts
